name: Run benchmarks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        benchmark: [nlp, file-enc, unix50, log-analysis, max-temp, media-conv, sklearn, covid-mts, riker, oneliners, web-index, bio]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y --no-install-recommends \
            curl wget unzip git \
            autoconf automake libtool build-essential gawk pkg-config \
            python3-pip
          pip3 install scikit-learn kaggle
          wget https://raw.githubusercontent.com/binpash/pash/main/scripts/up.sh
          sh up.sh
          export PASH_TOP="$PWD/pash/"

      - name: Set execute permissions for main.sh
        run: chmod +x main.sh

      - name: Run Benchmark for ${{ matrix.benchmark }}
        run: |
          export PASH_TOP="$PWD/pash/"
          "$PASH_TOP/pa.sh" -c "./main.sh ${{ matrix.benchmark }} --small"

      - name: Upload .out and .err files
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.benchmark }}-logs
          path: ${{ matrix.benchmark }}/${{ matrix.benchmark }}.*
          if-no-files-found: error
